// @generated by tools/gen_model. Do not edit manually.

#![allow(dead_code)]

pub const DEVICE_NAME: &str = "morphIIC P0";
pub const I2C_ADDRESS_7BIT: u8 = 0x42;
pub const ADDR_WIDTH_BITS: u8 = 8;
pub const REG_COUNT: usize = 256;
pub const DEFAULT_FILL: u8 = 0xFF;
pub const AUTO_INCREMENT: bool = true;

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Access {
    Ro,
    Rw,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct RegisterSpec {
    pub addr: u8,
    pub default: u8,
    pub access: Access,
    pub name: &'static str,
}

pub const REGISTERS: &[RegisterSpec] = &[
    RegisterSpec { addr: 0x00, default: 0x12, access: Access::Ro, name: "REG1" },
    RegisterSpec { addr: 0x01, default: 0x34, access: Access::Ro, name: "REG2" },
    RegisterSpec { addr: 0x10, default: 0x00, access: Access::Rw, name: "REG3" },
    RegisterSpec { addr: 0x11, default: 0x00, access: Access::Rw, name: "REG4" },
    RegisterSpec { addr: 0x20, default: 0xA0, access: Access::Ro, name: "REG5" },
    RegisterSpec { addr: 0x21, default: 0xA1, access: Access::Ro, name: "REG6" },
];
