// Generated by tools/gen_model. Do not edit manually.

#![allow(dead_code)]

pub const DEVICE_NAME: &str = "morphIIC";
pub const I2C_ADDRESS_7BIT: u8 = 0x42;
pub const I2C_INTERNAL_PULLUPS: bool = true;
pub const I2C_RESPOND_TO_GENERAL_CALL: bool = true;
pub const REG_COUNT: usize = 256;
pub const DEFAULT_FILL: u8 = 0xFF;
pub const AUTO_INCREMENT: bool = true;
pub const MAX_HOST_STREAM_REGS: usize = 9;
pub const HOST_STREAM_BUFFER_CAPACITY: usize = 2048;
pub const EMBEDDED_CSV_BUDGET_BYTES: usize = 32768;
pub const EMBEDDED_CSV_TOTAL_BYTES: usize = 6;

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Access {
    Ro,
    Rw,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum CsvMode {
    Embedded,
    HostStream,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct RegisterSpec {
    pub addr: u8,
    pub default: u8,
    pub access: Access,
    pub name: &'static str,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct CsvRegisterSpec {
    pub addr: u8,
    pub mode: CsvMode,
    pub data: &'static [u8],
}

pub const REGISTERS: &[RegisterSpec] = &[
    RegisterSpec { addr: 0x00, default: 0x12, access: Access::Ro, name: "REG1" },
    RegisterSpec { addr: 0x01, default: 0x34, access: Access::Ro, name: "REG2" },
    RegisterSpec { addr: 0x10, default: 0x00, access: Access::Rw, name: "REG3" },
    RegisterSpec { addr: 0x11, default: 0x00, access: Access::Rw, name: "REG4" },
    RegisterSpec { addr: 0x20, default: 0xA0, access: Access::Ro, name: "REG5_EMBEDDED" },
    RegisterSpec { addr: 0x21, default: 0xA1, access: Access::Ro, name: "REG6_HOST_STREAM" },
];

const CSV_DATA_0: &[u8] = &
[
    0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xFF, 
];

pub const CSV_REGISTERS: &[CsvRegisterSpec] = &[
    CsvRegisterSpec { addr: 0x20, mode: CsvMode::Embedded, data: CSV_DATA_0 },
    CsvRegisterSpec { addr: 0x21, mode: CsvMode::HostStream, data: &[] },
];

pub const CSV_INDEX_BY_ADDR: [i16; REG_COUNT] = [
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    0, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
];

pub const HOST_STREAM_COUNT: usize = 1;
pub const HOST_STREAM_ADDRS: [u8; HOST_STREAM_COUNT] = [
    0x21, 
];

pub const HOST_STREAM_INDEX_BY_ADDR: [i16; REG_COUNT] = [
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
];
