use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail, ensure};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct DeviceModel {
    pub device_name: String,
    pub i2c_address_7bit: u8,
    pub addr_width_bits: u8,
    pub reg_count: u16,
    pub default_fill: u8,
    pub auto_increment: bool,
    pub registers: Vec<RegisterDef>,
}

#[derive(Debug, Deserialize, Clone)]
pub struct RegisterDef {
    pub addr: u16,
    pub default: u8,
    pub access: Access,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Deserialize, Clone, Copy, Eq, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum Access {
    Ro,
    Rw,
}

fn validate(model: &DeviceModel) -> Result<()> {
    ensure!(
        model.addr_width_bits == 8,
        "MVP requires addr_width_bits == 8, got {}",
        model.addr_width_bits
    );
    ensure!(
        model.i2c_address_7bit <= 0x7f,
        "i2c_address_7bit must be <= 0x7f"
    );
    ensure!(model.reg_count > 0, "reg_count must be > 0");
    ensure!(
        model.reg_count <= 256,
        "reg_count must be <= 256 for 8-bit addresses"
    );

    let mut seen = [false; 256];
    for reg in &model.registers {
        ensure!(
            reg.addr < model.reg_count,
            "register addr {} is outside reg_count {}",
            reg.addr,
            model.reg_count
        );
        let idx = reg.addr as usize;
        if seen[idx] {
            bail!("duplicate register addr {}", reg.addr);
        }
        seen[idx] = true;
    }

    Ok(())
}

pub fn parse_model(model_json: &str) -> Result<DeviceModel> {
    let model: DeviceModel = serde_json::from_str(model_json).context("parsing model JSON")?;
    validate(&model)?;
    Ok(model)
}

pub fn generate_model_rs(model: &DeviceModel) -> String {
    let mut out = String::new();

    let mut registers = model.registers.clone();
    registers.sort_by_key(|r| r.addr);

    let _ = writeln!(
        out,
        "// @generated by tools/gen_model. Do not edit manually."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "#![allow(dead_code)]");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "pub const DEVICE_NAME: &str = {:?};",
        model.device_name
    );
    let _ = writeln!(
        out,
        "pub const I2C_ADDRESS_7BIT: u8 = 0x{:02X};",
        model.i2c_address_7bit
    );
    let _ = writeln!(
        out,
        "pub const ADDR_WIDTH_BITS: u8 = {};",
        model.addr_width_bits
    );
    let _ = writeln!(out, "pub const REG_COUNT: usize = {};", model.reg_count);
    let _ = writeln!(
        out,
        "pub const DEFAULT_FILL: u8 = 0x{:02X};",
        model.default_fill
    );
    let _ = writeln!(
        out,
        "pub const AUTO_INCREMENT: bool = {};",
        model.auto_increment
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "#[derive(Copy, Clone, Debug, Eq, PartialEq)]");
    let _ = writeln!(out, "pub enum Access {{");
    let _ = writeln!(out, "    Ro,");
    let _ = writeln!(out, "    Rw,");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "#[derive(Copy, Clone, Debug, Eq, PartialEq)]");
    let _ = writeln!(out, "pub struct RegisterSpec {{");
    let _ = writeln!(out, "    pub addr: u8,");
    let _ = writeln!(out, "    pub default: u8,");
    let _ = writeln!(out, "    pub access: Access,");
    let _ = writeln!(out, "    pub name: &'static str,");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "pub const REGISTERS: &[RegisterSpec] = &[");

    for reg in registers {
        let access = match reg.access {
            Access::Ro => "Access::Ro",
            Access::Rw => "Access::Rw",
        };
        let _ = writeln!(
            out,
            "    RegisterSpec {{ addr: 0x{:02X}, default: 0x{:02X}, access: {}, name: {:?} }},",
            reg.addr, reg.default, access, reg.name,
        );
    }

    let _ = writeln!(out, "];");

    out
}

pub fn generate_from_paths(input_path: &Path, output_path: &Path) -> Result<()> {
    let input = fs::read_to_string(input_path)
        .with_context(|| format!("reading {}", input_path.display()))?;
    let model = parse_model(&input)?;
    let generated = generate_model_rs(&model);
    fs::write(output_path, generated)
        .with_context(|| format!("writing {}", output_path.display()))?;
    Ok(())
}
