[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip RP2040" # for jtag
runner = "elf2uf2-rs --deploy --serial --verbose" # for elf2uf2

[alias]
build-fw = "build -p mimiic-firmware --target thumbv6m-none-eabi"
check-fw = "check -p mimiic-firmware --target thumbv6m-none-eabi"
run-fw = "run -p mimiic-firmware --target thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
